
SCREEN_WIDTH = 900
SCREEN_HEIGHT = 900
FPS = 400

ACTIVE_MUSIC = 'music_1.mp3'

TEXT_EXTENSIONS = ['.txt']
IMG_EXTENSIONS = ['.png', '.bmp', '.jpg']
MUSIC_PATH = './music/'
DATA_PATH = './data/'

WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)

SPRINGS = "Springs"
CONSTANT_FORCE = "Constant force"
SIMULATION_METHODS = [SPRINGS, CONSTANT_FORCE]

